// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: parser.proto
#ifndef GRPC_parser_2eproto__INCLUDED
#define GRPC_parser_2eproto__INCLUDED

#include "parser.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace MySqlParseService {

class ParseService final {
 public:
  static constexpr char const* service_full_name() {
    return "MySqlParseService.ParseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::MySqlParseService::CreateTableResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::CreateTableResponse>> AsyncParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::CreateTableResponse>>(AsyncParseCreateTableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::CreateTableResponse>> PrepareAsyncParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::CreateTableResponse>>(PrepareAsyncParseCreateTableRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ParseCreateTable(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::CreateTableResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void ParseCreateTable(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::CreateTableResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::CreateTableResponse>* AsyncParseCreateTableRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::CreateTableResponse>* PrepareAsyncParseCreateTableRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::MySqlParseService::CreateTableResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::CreateTableResponse>> AsyncParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::CreateTableResponse>>(AsyncParseCreateTableRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::CreateTableResponse>> PrepareAsyncParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::CreateTableResponse>>(PrepareAsyncParseCreateTableRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response, std::function<void(::grpc::Status)>) override;
      void ParseCreateTable(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::CreateTableResponse* response, std::function<void(::grpc::Status)>) override;
      void ParseCreateTable(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void ParseCreateTable(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::CreateTableResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MySqlParseService::CreateTableResponse>* AsyncParseCreateTableRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MySqlParseService::CreateTableResponse>* PrepareAsyncParseCreateTableRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ParseCreateTable_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ParseCreateTable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ParseCreateTable() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ParseCreateTable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParseCreateTable(::grpc::ServerContext* context, ::MySqlParseService::Request* request, ::grpc::ServerAsyncResponseWriter< ::MySqlParseService::CreateTableResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ParseCreateTable<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ParseCreateTable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_ParseCreateTable() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::MySqlParseService::Request, ::MySqlParseService::CreateTableResponse>(
          [this](::grpc::ServerContext* context,
                 const ::MySqlParseService::Request* request,
                 ::MySqlParseService::CreateTableResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->ParseCreateTable(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_ParseCreateTable(
        ::grpc::experimental::MessageAllocator< ::MySqlParseService::Request, ::MySqlParseService::CreateTableResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::MySqlParseService::Request, ::MySqlParseService::CreateTableResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ParseCreateTable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_ParseCreateTable<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ParseCreateTable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ParseCreateTable() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ParseCreateTable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ParseCreateTable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_ParseCreateTable() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ParseCreateTable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParseCreateTable(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ParseCreateTable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_ParseCreateTable() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->ParseCreateTable(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_ParseCreateTable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ParseCreateTable(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ParseCreateTable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ParseCreateTable() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::MySqlParseService::Request, ::MySqlParseService::CreateTableResponse>(std::bind(&WithStreamedUnaryMethod_ParseCreateTable<BaseClass>::StreamedParseCreateTable, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ParseCreateTable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ParseCreateTable(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::CreateTableResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedParseCreateTable(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MySqlParseService::Request,::MySqlParseService::CreateTableResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ParseCreateTable<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ParseCreateTable<Service > StreamedService;
};

}  // namespace MySqlParseService


#endif  // GRPC_parser_2eproto__INCLUDED
