// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: parser.proto

#include "parser.pb.h"
#include "parser.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace MySqlParseService {

static const char* ParseService_method_names[] = {
  "/MySqlParseService.ParseService/ParseQuery",
};

std::unique_ptr< ParseService::Stub> ParseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ParseService::Stub> stub(new ParseService::Stub(channel));
  return stub;
}

ParseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ParseQuery_(ParseService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ParseService::Stub::ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::MySqlParseService::Response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ParseQuery_, context, request, response);
}

void ParseService::Stub::experimental_async::ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ParseQuery_, context, request, response, std::move(f));
}

void ParseService::Stub::experimental_async::ParseQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ParseQuery_, context, request, response, std::move(f));
}

void ParseService::Stub::experimental_async::ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ParseQuery_, context, request, response, reactor);
}

void ParseService::Stub::experimental_async::ParseQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ParseQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>* ParseService::Stub::AsyncParseQueryRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MySqlParseService::Response>::Create(channel_.get(), cq, rpcmethod_ParseQuery_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>* ParseService::Stub::PrepareAsyncParseQueryRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::MySqlParseService::Response>::Create(channel_.get(), cq, rpcmethod_ParseQuery_, context, request, false);
}

ParseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ParseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ParseService::Service, ::MySqlParseService::Request, ::MySqlParseService::Response>(
          std::mem_fn(&ParseService::Service::ParseQuery), this)));
}

ParseService::Service::~Service() {
}

::grpc::Status ParseService::Service::ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace MySqlParseService

