// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: parser.proto
#ifndef GRPC_parser_2eproto__INCLUDED
#define GRPC_parser_2eproto__INCLUDED

#include "parser.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace MySqlParseService {

class ParseService final {
 public:
  static constexpr char const* service_full_name() {
    return "MySqlParseService.ParseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::MySqlParseService::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::Response>> AsyncParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::Response>>(AsyncParseQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::Response>> PrepareAsyncParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::Response>>(PrepareAsyncParseQueryRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ParseQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void ParseQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::Response>* AsyncParseQueryRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MySqlParseService::Response>* PrepareAsyncParseQueryRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::MySqlParseService::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>> AsyncParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>>(AsyncParseQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>> PrepareAsyncParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>>(PrepareAsyncParseQueryRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, std::function<void(::grpc::Status)>) override;
      void ParseQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::Response* response, std::function<void(::grpc::Status)>) override;
      void ParseQuery(::grpc::ClientContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void ParseQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::MySqlParseService::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>* AsyncParseQueryRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MySqlParseService::Response>* PrepareAsyncParseQueryRaw(::grpc::ClientContext* context, const ::MySqlParseService::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ParseQuery_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ParseQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ParseQuery() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ParseQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParseQuery(::grpc::ServerContext* context, ::MySqlParseService::Request* request, ::grpc::ServerAsyncResponseWriter< ::MySqlParseService::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ParseQuery<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ParseQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_ParseQuery() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::MySqlParseService::Request, ::MySqlParseService::Response>(
          [this](::grpc::ServerContext* context,
                 const ::MySqlParseService::Request* request,
                 ::MySqlParseService::Response* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->ParseQuery(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_ParseQuery(
        ::grpc::experimental::MessageAllocator< ::MySqlParseService::Request, ::MySqlParseService::Response>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::MySqlParseService::Request, ::MySqlParseService::Response>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ParseQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_ParseQuery<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ParseQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ParseQuery() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ParseQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ParseQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_ParseQuery() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ParseQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParseQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ParseQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_ParseQuery() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->ParseQuery(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_ParseQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ParseQuery(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ParseQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ParseQuery() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::MySqlParseService::Request, ::MySqlParseService::Response>(std::bind(&WithStreamedUnaryMethod_ParseQuery<BaseClass>::StreamedParseQuery, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ParseQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ParseQuery(::grpc::ServerContext* context, const ::MySqlParseService::Request* request, ::MySqlParseService::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedParseQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MySqlParseService::Request,::MySqlParseService::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ParseQuery<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ParseQuery<Service > StreamedService;
};

}  // namespace MySqlParseService


#endif  // GRPC_parser_2eproto__INCLUDED
