#!/bin/bash

if [ $# -lt 1 ]
then
  echo "Usage: $0 [mysql]"
  exit
fi 

LOCATION=/usr/local/lib/antlr-4.7.2-complete.jar
case "$1" in
  "mysql") echo "Building MySQL parser"
    java -jar $LOCATION -Dlanguage=Cpp -listener -visitor -o ../mysql -package parsers MySQLLexer.g4 MySQLParser.g4
  ;;
 *) echo "Unknown parser type $1"
 exit 1
 ;;
esac

